---
# ansible-role-apt (ctorgalson.apt) vars.

# Notes:
#  - In general, we're installing packages here rather than in individual roles
#    such as ansible-role-oh-my-zsh for visibility.
apt_packages:
  - name: "byobu"
  - name: "curl"
  - name: "git"
  - name: "git-extras"
  - name: "glances"
  - name: "httpie"
  - name: "lynis"
  - name: "mosh"
  - name: "neofetch"
  - name: "openssh-server"
  - name: "pv"
  - name: "silversearcher-ag"
  - name: "speedtest-cli"
  - name: "unzip"
  - name: "vim"
  - name: "zsh"
